stages:
  data_cleaning:
    cmd: python src/data/data_cleaning.py
    deps:
      - data/raw/swiggy.csv
      - src/data/data_cleaning.py
    outs:
      - data/cleaned/swiggy_cleaned.csv

  data_preparation:
    cmd: python src/data/data_preparation.py 
    deps: 
      - data/cleaned/swiggy_cleaned.csv
      - src/data/data_preparation.py
    outs:
      - data/interim/
    params:
      - test_size
      - random_state

  data_preprocessing:
    cmd: python src/features/data_preprocessing.py
    deps:
    - data/interim/train.csv
    - data/interim/test.csv
    - src/features/data_preprocessing.py
    outs:
    - data/processed/train_processed.csv
    - data/processed/test_processed.csv
    - models/preprocessor.joblib
