Data_Preparation:
  test_size: 0.2
  random_state: 42
Train:
  Random_Forest:
    n_estimators: 400
    criterion: 'squared_error'
    max_depth: 14
    max_features: 0.7
    min_samples_leaf: 5
    verbose: 1
    n_jobs: -1

  LightGBM:
    n_estimators: 200
    max_depth: 15
    learning_rate: 0.025811265327068796
    num_leaves: 84
    n_jobs: -1